### ISSUE TITLE
Create variant of size_warning.py to prevent commits of large files without git-lfs

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#91] opened 2017-08-09 18:19 UTC
This task will:

- Create variant of our file size checker used for release, to prevent commits of large files when git-lfs is turned off.

- Ensure that .gitattributes stays stable even when git-lfs is turned off.

**Comment by Shun-Yang** [comment] 2017-08-25 18:08
@stanfordquan @yuchuan2016 , I took a look on this, but not sure how to do this easily. It seems like we need something like a git hook (see [here](https://stackoverflow.com/questions/7147699/limiting-file-size-in-git-repository/7147764#7147764)). You can go ahead and take this task if you think you may be more familiar with this.

**Comment by stanfordquan** [comment] 2017-08-26 00:01
No idea what that is, but happy to learn it.

**Comment by Shun-Yang** [comment] 2017-08-26 19:49
I think I may have an idea. 
1. Check if `git-lfs` is turned off first 
2. If turned off, call a function in gslab_scons, that function will check if  `.git/hooks/` contains a hook named `check_size`
3. If not, will automatically create a size hook inside `.git/hooks/` with a pre-defined size limit. 
4. The key will be to write such a hook, which I think has some templates online.

**Comment by Shun-Yang** [comment] 2017-08-27 18:47
Besides the approach like above, another approach is ask the users to use `pre-commit` [platform](http://pre-commit.com/) and install different [hooks](https://github.com/pre-commit/pre-commit-hooks).

**Comment by Shun-Yang** [comment] 2017-08-28 16:39
@stanfordquan @yuchuan2016 @arosenbe , I want to get your opinion on this. Essentially, in order to trigger a warning whenever a user commit a large file, we want to use pre-commit git [hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). A git hook can be written in any executable language and is placed in the directory as `.git/hooks/pre-commit`. To accomplish this, we basically have the following ways: 

1. Do everything ourselves. It basically involves steps listed [here](https://github.com/gslab-econ/gslab_python/issues/91#issuecomment-325158183). This will likely be more buggy but we have more control over. The potential problems I suspect will be: 1. OS issue,  2. if user already defined a `pre-commit` hook, how to add another one, 3. I think this will involve decent amount of time. 

2. List `pre-commit` platform python module [here](http://pre-commit.com/) as an option for the users. They can install it by `pip install pre-commit` and then install a hook very easily by specifying it in `.pre-commit-config.yaml` in their directory (like [here](https://github.com/pre-commit/pre-commit-hooks)). This way, the problems are solved via the external packages.

Let me know if you have any thoughts or we can talk over during our meeting today.

**Comment by yuchuan2016** [comment] 2017-08-28 17:49
@Shun-Yang , can we directly edit the `.git/hooks/pre-commit` in our template to add another check before commit, instead of writing our own script? The instruction of `pre-commit` is 
> An example hook script to verify what is about to be committed.
Called by "git commit" with no arguments.  The hook should
exit with non-zero status after issuing an appropriate message if
it wants to stop the commit.

One of their example is to
> Prevent non-ASCII filenames from being added to the repository.

which seems similar to what we want to do.

**Comment by Shun-Yang** [comment] 2017-08-28 17:53
@yuchuan2016 , the problem is that the directory `/.git/` is not versioned and you probably don't want everyone to have the same git setup (they are likely to have their personal preference etc.).

**Comment by yuchuan2016** [comment] 2017-08-28 17:54
Oh I see.

**Comment by Shun-Yang** [comment] 2017-08-28 18:42
Meeting notes: will just create two size limit if the user has lfs or not. Gonna abandon the whole hook thing.

**Comment by Shun-Yang** [comment] 2017-08-28 21:40
If there is git-lfs, then files of type like *.pdf will be loaded with git-lfs regardless of the size. So we still need to specify a size warning for files like *.txt. Also, even for git-lfs, the free storage space is 2GB. If there is no git-lfs, we should set a smaller file size limit, warn people and also recommend them using lfs in this case. Note that github recommend the repo total size to be < 1GB. 

My proposal is to make the file size limit to be 2MB, total size limit to be 500MB with git-lfs (our current standard) and the file size limit to be 0.5MB, total size limit to be 125MB without git-lfs.

@stanfordquan @yuchuan2016 @arosenbe, FYI. Let me know if you have any suggestion/comments.

**Comment by Shun-Yang** [comment] 2017-08-30 08:10
Closing the task. Pull request is at #118. Summary: I modified `scons_debrief` and `size_warning` to have different size limits if git-lfs not present.

**Closed by Shun-Yang** 2017-08-30 08:10 UTC
